### ISSUE TITLE
Java Streams chapter: examples more intent revealing and show similarities to sql

### ISSUE THREAD

**Issue by k3b** [forax/java-guide#10]
The stream chapter dos not have any info, why i should use them. Maybe it is helpfull to compare streams to database-sql

here are some examples:

SQL: SELECT ... FROM persons WHERE name like 'E%'
java-Streams: persons.stream().filter(person -> person.firstname.startsWith("E")

map: convert list elements of Person into a list of Employee

SQL: SELECT firstname || ' ' || lastname as name, today() - birthday as age FROM persons WHERE ....
java-Streams: persons.stream().map(person -> new Employee(person.getFirstname + " " + person.getLastname, getDifferenceInYears(new Date(), person.getBirthday()))

public class Employee {
   public Employee(String name, int age)

**Comment by forax** [comment]
> The stream chapter dos not have any info, why i should use them. Maybe it is helpful to compare streams to database-sql

I agree that there are not a lot of info about why using streams.
I don't think that using SQL helps about the why, it helps to assemble the stream query but not really to understand why you may use a stream given that Java exists almost 20 years without streams.

The main reason is that it makes the code more readable, you can express more concisely what you want without having to explain how to get it.
I will try to reword the introduction of this chapter during this week end.

**Comment by forax** [comment]
see https://github.com/forax/java-guide/blob/master/guide/chapter25-stream.md
