### ISSUE TITLE
`toUpperCase()`  could return unexpected result

### ISSUE THREAD

**Issue by wangweij** [forax/java-guide#19]
At https://github.com/forax/java-guide/blob/master/guide/chapter01-basic_types.md?plain=1#L111,  I dare not call `toUpperCase()` or `toLowerCase()` without the `Locale.ROOT` argument.

**Comment by forax** [comment]
Yes, it will be a mess if the Locale is Turkish

**Comment by wangweij** [comment]
Yes, that's the way I learned about it. Just not sure if this will bring unnecessary complexity to a new learner's guide.

**Comment by forax** [comment]
Updated in https://github.com/forax/java-guide/commit/85c179cba3f73665c8e57b52a3de0d0375a6afd5

**Comment by forax** [comment]
I've added a sentence trying to explain in simple term why Locale.ROOT should be used
